#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "Lexer.rb"
require_relative "astParser.rb"

class SyntacticError < RuntimeError

    def initialize(token)
        @token = token
    end

    def to_s
        puts "SYNTACTIC ERROR FOUND:"
        if @token.eql? "$" then
            puts "Unexpected EOF"
        else
            puts "ERROR: unexpected token '#{@token.str}' at line #{@token.line}, column #{@token.column}"   
        end    
    end
end


class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 223)

def initialize(lexer)
    @lexer = lexer
end

def on_error(id, token, stack)
	SyntacticError.new(token).to_s
	exit
    #raise SyntacticError::new(token)
end

def next_token
    if @lexer.haySiguiente then
        token = @lexer.tokenSiguiente;
        return [token.type, token]
    else
        return nil
    end
end

def parse
    do_parse
end


...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    97,    43,     9,    10,    11,     2,    81,    82,    83,    79,
    80,    96,    95,    84,    86,    85,    87,    88,    89,    92,
    94,    93,    90,    91,    97,   163,   164,     3,    31,    32,
    81,    82,    83,    79,    80,    96,    95,    84,    86,    85,
    87,    88,    89,    92,    94,    93,    90,    91,    30,    30,
    97,    30,    42,    39,    40,   135,    81,    82,    83,    79,
    80,    96,    95,    84,    86,    85,    87,    88,    89,    92,
    94,    93,    90,    91,    97,    41,    30,    64,    65,   139,
    81,    82,    83,    79,    80,    96,    95,    84,    86,    85,
    87,    88,    89,    92,    94,    93,    90,    91,    50,    51,
    52,    49,    70,    72,    72,   154,    97,    48,    50,    51,
    52,    49,    81,    82,    83,    79,    80,    48,    50,    51,
    52,    49,    74,    30,   107,   109,   111,    48,    97,   162,
    50,    51,    52,    49,    81,    82,    83,    79,    80,    48,
   160,   114,    97,    60,    30,    61,    59,    62,    97,   161,
    97,    45,    97,    60,    30,    61,    59,    62,    81,    82,
    83,    45,    97,    60,    30,    61,    59,    62,    81,    82,
    83,    45,    97,    97,   136,    60,    30,    61,    59,    62,
    30,   138,   141,    45,    50,    51,    52,    49,    97,    97,
    97,   145,   147,    48,    50,    51,    52,    49,    97,    72,
   151,   156,   nil,    48,    81,    82,    83,    79,    80,    96,
    95,    84,    86,    85,    87,    88,    89,    92,    94,    93,
    90,    91,   nil,   nil,   nil,    50,    51,    52,    49,    60,
    30,    61,    59,    62,    48,   nil,   nil,    45,   nil,    60,
    30,    61,    59,    62,   nil,   nil,   nil,    45,   nil,   nil,
   nil,    98,    50,    51,    52,    49,   nil,   nil,   nil,   nil,
   nil,    48,   nil,   nil,   nil,   nil,    50,    51,    52,    49,
    60,    30,    61,    59,    62,    48,   nil,   nil,    45,    50,
    51,    52,    49,   nil,   nil,   nil,   nil,   nil,    48,   nil,
   nil,   nil,   nil,    50,    51,    52,    49,    60,    30,    61,
    59,    62,    48,   nil,   nil,    45,   nil,    50,    51,    52,
    49,    60,    30,    61,    59,    62,    48,   nil,   nil,    45,
    50,    51,    52,    49,    60,    30,    61,    59,    62,    48,
   nil,   nil,    45,   nil,    50,    51,    52,    49,    60,    30,
    61,    59,    62,    48,   nil,   nil,    45,   nil,    50,    51,
    52,    49,    60,    30,    61,    59,    62,    48,   nil,   nil,
    45,    50,    51,    52,    49,    60,    30,    61,    59,    62,
    48,   nil,   nil,    45,   nil,    50,    51,    52,    49,    60,
    30,    61,    59,    62,    48,   nil,   nil,    45,   nil,    50,
    51,    52,    49,    60,    30,    61,    59,    62,    48,   nil,
   nil,    45,    50,    51,    52,    49,    60,    30,    61,    59,
    62,    48,   nil,   nil,    45,   nil,    50,    51,    52,    49,
    60,    30,    61,    59,    62,    48,   nil,   nil,    45,   nil,
    50,    51,    52,    49,    60,    30,    61,    59,    62,    48,
   nil,   nil,    45,    50,    51,    52,    49,    60,    30,    61,
    59,    62,    48,   nil,   nil,    45,   nil,    50,    51,    52,
    49,    60,    30,    61,    59,    62,    48,   nil,   nil,    45,
   nil,    50,    51,    52,    49,    60,    30,    61,    59,    62,
    48,   nil,   nil,    45,    50,    51,    52,    49,    60,    30,
    61,    59,    62,    48,   nil,   nil,    45,   nil,    50,    51,
    52,    49,    60,    30,    61,    59,    62,    48,   nil,   nil,
    45,   nil,    50,    51,    52,    49,    60,    30,    61,    59,
    62,    48,   nil,   nil,    45,    50,    51,    52,    49,    60,
    30,    61,    59,    62,    48,   nil,   nil,    45,   nil,    50,
    51,    52,    49,    60,    30,    61,    59,    62,    48,   nil,
   nil,    45,   nil,    50,    51,    52,    49,    60,    30,    61,
    59,    62,    48,   nil,   nil,    45,    50,    51,    52,    49,
    60,    30,    61,    59,    62,    48,   nil,   nil,    45,   nil,
    50,    51,    52,    49,    60,    30,    61,    59,    62,    48,
   nil,   nil,    45,   nil,    50,    51,    52,    49,    60,    30,
    61,    59,    62,    48,   nil,   nil,    45,    50,    51,    52,
    49,    60,    30,    61,    59,    62,    48,   nil,   nil,    45,
   nil,    50,    51,    52,    49,    60,    30,    61,    59,    62,
    48,   nil,   nil,    45,   nil,    50,    51,    52,    49,    60,
    30,    61,    59,    62,    48,   nil,   nil,    45,    50,    51,
    52,    49,    60,    30,    61,    59,    62,    48,   nil,   nil,
    45,   nil,    50,    51,    52,    49,    60,    30,    61,    59,
    62,    48,   nil,   nil,    45,   nil,    50,    51,    52,    49,
    60,    30,    61,    59,    62,    48,   nil,   nil,    45,    50,
    51,    52,    49,    60,    30,    61,    59,    62,    48,   nil,
   nil,    45,   nil,   nil,   nil,   nil,   nil,    60,    30,    61,
    59,    62,   nil,   nil,   nil,    45,   nil,   nil,   nil,   nil,
   nil,    60,    30,    61,    59,    62,   nil,   nil,   nil,    45,
   nil,   nil,   nil,   nil,    60,    30,    61,    59,    62,    97,
   nil,   nil,    45,   nil,   nil,    81,    82,    83,    79,    80,
    96,    95,    84,    86,    85,    87,    88,    89,    92,    94,
    93,    90,    91,    97,   nil,   nil,   nil,   nil,   nil,    81,
    82,    83,    79,    80,    96,    95,    84,    86,    85,    87,
    88,    89,    92,    94,    93,    90,    91,   nil,   nil,   nil,
   nil,   152,   nil,   nil,   nil,   nil,    97,   nil,   nil,   nil,
   nil,   159,    81,    82,    83,    79,    80,    96,    95,    84,
    86,    85,    87,    88,    89,    92,    94,    93,    90,    91,
   nil,   nil,   nil,   nil,   nil,   nil,   113,    97,   nil,   nil,
   nil,   nil,   106,    81,    82,    83,    79,    80,    96,    95,
    84,    86,    85,    87,    88,    89,    92,    94,    93,    90,
    91,   140,    97,   nil,   nil,   nil,   nil,   nil,    81,    82,
    83,    79,    80,    96,    95,    84,    86,    85,    87,    88,
    89,    92,    94,    93,    90,    91,   142,    97,   nil,   nil,
   nil,   nil,   nil,    81,    82,    83,    79,    80,    96,    95,
    84,    86,    85,    87,    88,    89,    92,    94,    93,    90,
    91,     2,     5,     9,    10,    11,    22,    23,    24,    25,
   nil,    26,    27,   nil,   nil,     2,   nil,   nil,    28,    29,
    22,    23,    24,    25,    30,    26,    27,   nil,   nil,     2,
   nil,   nil,    28,    29,    22,    23,    24,    25,    30,    26,
    27,   nil,   nil,   nil,   nil,   nil,    28,    29,   nil,   nil,
   nil,     2,    30,     9,    10,    11,    22,    23,    24,    25,
   nil,    26,    27,   nil,   nil,   nil,   nil,   nil,    28,    29,
    97,   nil,   nil,   nil,    30,   nil,    81,    82,    83,    79,
    80,    96,    95,    84,    86,    85,    87,    88,    89,    92,
    94,    93,    90,    91,    97,   nil,   nil,   nil,   nil,   nil,
    81,    82,    83,    79,    80,    96,    95,    84,    86,    85,
    87,    88,    89,    92,    94,    93,    90,    91,    97,   nil,
   nil,   nil,   nil,   nil,    81,    82,    83,    79,    80,    96,
    95,    84,    86,    85,    87,    88,    89,    92,    94,    93,
    90,    91,     2,   nil,     9,    10,    11,    22,    23,    24,
    25,   nil,    26,    27,   nil,   nil,   nil,   nil,   nil,    28,
    29,   nil,   nil,   nil,     2,    30,     9,    10,    11,    22,
    23,    24,    25,   nil,    26,    27,   nil,   nil,   nil,   nil,
   nil,    28,    29,    97,   nil,   nil,   nil,    30,   nil,    81,
    82,    83,    79,    80,    96,    95,    84,    86,    85,    87,
    88,    89,    92,    94,    93,    90,    91,     2,   nil,     9,
    10,    11,    22,    23,    24,    25,   nil,    26,    27,   nil,
   nil,   nil,   nil,   nil,    28,    29,   nil,   nil,   nil,     2,
    30,     9,    10,    11,    22,    23,    24,    25,   nil,    26,
    27,   nil,   nil,   nil,   nil,   nil,    28,    29,   nil,   nil,
   nil,     2,    30,     9,    10,    11,    22,    23,    24,    25,
   nil,    26,    27,   nil,   nil,   nil,   nil,   nil,    28,    29,
   nil,   nil,   nil,     2,    30,     9,    10,    11,    22,    23,
    24,    25,   nil,    26,    27,   nil,   nil,   nil,   nil,   nil,
    28,    29,   nil,   nil,   nil,     2,    30,     9,    10,    11,
    22,    23,    24,    25,   nil,    26,    27,   nil,   nil,   nil,
   nil,   nil,    28,    29,    97,   nil,   nil,   nil,    30,   nil,
    81,    82,    83,    79,    80,    96,    95,    84,    86,    85,
    87,    88,    89,    92,    94,    93,    90,    97,   nil,   nil,
   nil,   nil,   nil,    81,    82,    83,    79,    80,    96,    95,
    84,    86,    85,    87,    88,    89,    92,    94,    93,    97,
   nil,   nil,   nil,   nil,   nil,    81,    82,    83,    79,    80,
    96,    95,    84,    86,    85,    87,    88,    89,    92,    94,
    97,   nil,   nil,   nil,   nil,   nil,    81,    82,    83,    79,
    80,    96,    95,    84,    86,    85,    87,    88,    89,    92,
    97,   nil,   nil,   nil,   nil,   nil,    81,    82,    83,    79,
    80,    96,    95,    84,    86,    85,    87,    88,    89,    97,
   nil,   nil,   nil,   nil,   nil,    81,    82,    83,    79,    80,
    96,    95,   -77,   -77,   -77,   -77,    97,   nil,   nil,   nil,
   nil,   nil,    81,    82,    83,    79,    80,    96,    95,   -77,
   -77,   -77,   -77,    97,   nil,   nil,   nil,   nil,   nil,    81,
    82,    83,    79,    80,    96,    95,   -77,   -77,   -77,   -77,
    97,   nil,   nil,   nil,   nil,   nil,    81,    82,    83,    79,
    80,    96,    95,   -77,   -77,   -77,   -77,    97,   nil,   nil,
   nil,   nil,   nil,    81,    82,    83,    79,    80,    96,    95,
    84,    86,    85,    87,    97,   nil,   nil,   nil,   nil,   nil,
    81,    82,    83,    79,    80,    96,    95,    84,    86,    85,
    87 ]

racc_action_check = [
   104,    21,     8,     8,     8,     0,   104,   104,   104,   104,
   104,   104,   104,   104,   104,   104,   104,   104,   104,   104,
   104,   104,   104,   104,   108,   159,   159,     1,     3,     4,
   108,   108,   108,   108,   108,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   108,   108,   108,     9,    10,
   146,    11,    21,    14,    15,   104,   146,   146,   146,   146,
   146,   146,   146,   146,   146,   146,   146,   146,   146,   146,
   146,   146,   146,   146,   158,    16,    22,    25,    26,   108,
   158,   158,   158,   158,   158,   158,   158,   158,   158,   158,
   158,   158,   158,   158,   158,   158,   158,   158,    23,    23,
    23,    23,    29,    35,    36,   146,   131,    23,    24,    24,
    24,    24,   131,   131,   131,   131,   131,    24,    27,    27,
    27,    27,    37,    65,    67,    71,    73,    27,   132,   158,
    42,    42,    42,    42,   132,   132,   132,   132,   132,    42,
   154,    77,    99,    23,    23,    23,    23,    23,   100,   154,
   101,    23,   115,    24,    24,    24,    24,    24,   115,   115,
   115,    24,   116,    27,    27,    27,    27,    27,   116,   116,
   116,    27,   102,   103,   105,    42,    42,    42,    42,    42,
   106,   107,   113,    42,    43,    43,    43,    43,   117,   118,
   119,   137,   139,    43,    45,    45,    45,    45,    47,   140,
   143,   148,   nil,    45,    47,    47,    47,    47,    47,    47,
    47,    47,    47,    47,    47,    47,    47,    47,    47,    47,
    47,    47,   nil,   nil,   nil,    48,    48,    48,    48,    43,
    43,    43,    43,    43,    48,   nil,   nil,    43,   nil,    45,
    45,    45,    45,    45,   nil,   nil,   nil,    45,   nil,   nil,
   nil,    47,    49,    49,    49,    49,   nil,   nil,   nil,   nil,
   nil,    49,   nil,   nil,   nil,   nil,    50,    50,    50,    50,
    48,    48,    48,    48,    48,    50,   nil,   nil,    48,    51,
    51,    51,    51,   nil,   nil,   nil,   nil,   nil,    51,   nil,
   nil,   nil,   nil,    52,    52,    52,    52,    49,    49,    49,
    49,    49,    52,   nil,   nil,    49,   nil,    64,    64,    64,
    64,    50,    50,    50,    50,    50,    64,   nil,   nil,    50,
    70,    70,    70,    70,    51,    51,    51,    51,    51,    70,
   nil,   nil,    51,   nil,    72,    72,    72,    72,    52,    52,
    52,    52,    52,    72,   nil,   nil,    52,   nil,    74,    74,
    74,    74,    64,    64,    64,    64,    64,    74,   nil,   nil,
    64,    79,    79,    79,    79,    70,    70,    70,    70,    70,
    79,   nil,   nil,    70,   nil,    80,    80,    80,    80,    72,
    72,    72,    72,    72,    80,   nil,   nil,    72,   nil,    81,
    81,    81,    81,    74,    74,    74,    74,    74,    81,   nil,
   nil,    74,    82,    82,    82,    82,    79,    79,    79,    79,
    79,    82,   nil,   nil,    79,   nil,    83,    83,    83,    83,
    80,    80,    80,    80,    80,    83,   nil,   nil,    80,   nil,
    84,    84,    84,    84,    81,    81,    81,    81,    81,    84,
   nil,   nil,    81,    85,    85,    85,    85,    82,    82,    82,
    82,    82,    85,   nil,   nil,    82,   nil,    86,    86,    86,
    86,    83,    83,    83,    83,    83,    86,   nil,   nil,    83,
   nil,    87,    87,    87,    87,    84,    84,    84,    84,    84,
    87,   nil,   nil,    84,    88,    88,    88,    88,    85,    85,
    85,    85,    85,    88,   nil,   nil,    85,   nil,    89,    89,
    89,    89,    86,    86,    86,    86,    86,    89,   nil,   nil,
    86,   nil,    90,    90,    90,    90,    87,    87,    87,    87,
    87,    90,   nil,   nil,    87,    91,    91,    91,    91,    88,
    88,    88,    88,    88,    91,   nil,   nil,    88,   nil,    92,
    92,    92,    92,    89,    89,    89,    89,    89,    92,   nil,
   nil,    89,   nil,    93,    93,    93,    93,    90,    90,    90,
    90,    90,    93,   nil,   nil,    90,    94,    94,    94,    94,
    91,    91,    91,    91,    91,    94,   nil,   nil,    91,   nil,
    95,    95,    95,    95,    92,    92,    92,    92,    92,    95,
   nil,   nil,    92,   nil,    96,    96,    96,    96,    93,    93,
    93,    93,    93,    96,   nil,   nil,    93,    97,    97,    97,
    97,    94,    94,    94,    94,    94,    97,   nil,   nil,    94,
   nil,    98,    98,    98,    98,    95,    95,    95,    95,    95,
    98,   nil,   nil,    95,   nil,   136,   136,   136,   136,    96,
    96,    96,    96,    96,   136,   nil,   nil,    96,   138,   138,
   138,   138,    97,    97,    97,    97,    97,   138,   nil,   nil,
    97,   nil,   141,   141,   141,   141,    98,    98,    98,    98,
    98,   141,   nil,   nil,    98,   nil,   145,   145,   145,   145,
   136,   136,   136,   136,   136,   145,   nil,   nil,   136,   152,
   152,   152,   152,   138,   138,   138,   138,   138,   152,   nil,
   nil,   138,   nil,   nil,   nil,   nil,   nil,   141,   141,   141,
   141,   141,   nil,   nil,   nil,   141,   nil,   nil,   nil,   nil,
   nil,   145,   145,   145,   145,   145,   nil,   nil,   nil,   145,
   nil,   nil,   nil,   nil,   152,   152,   152,   152,   152,   144,
   nil,   nil,   152,   nil,   nil,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   153,   nil,   nil,   nil,   nil,   nil,   153,
   153,   153,   153,   153,   153,   153,   153,   153,   153,   153,
   153,   153,   153,   153,   153,   153,   153,   nil,   nil,   nil,
   nil,   144,   nil,   nil,   nil,   nil,    66,   nil,   nil,   nil,
   nil,   153,    66,    66,    66,    66,    66,    66,    66,    66,
    66,    66,    66,    66,    66,    66,    66,    66,    66,    66,
   nil,   nil,   nil,   nil,   nil,   nil,    76,    76,   nil,   nil,
   nil,   nil,    66,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,   112,   112,   nil,   nil,   nil,   nil,   nil,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   133,   133,   nil,   nil,
   nil,   nil,   nil,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,     2,     2,     2,     2,     2,     2,     2,     2,     2,
   nil,     2,     2,   nil,   nil,     6,   nil,   nil,     2,     2,
     6,     6,     6,     6,     2,     6,     6,   nil,   nil,    12,
   nil,   nil,     6,     6,    12,    12,    12,    12,     6,    12,
    12,   nil,   nil,   nil,   nil,   nil,    12,    12,   nil,   nil,
   nil,    28,    12,    28,    28,    28,    28,    28,    28,    28,
   nil,    28,    28,   nil,   nil,   nil,   nil,   nil,    28,    28,
    75,   nil,   nil,   nil,    28,   nil,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    78,   nil,   nil,   nil,   nil,   nil,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,   110,   nil,
   nil,   nil,   nil,   nil,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   135,   nil,   135,   135,   135,   135,   135,   135,
   135,   nil,   135,   135,   nil,   nil,   nil,   nil,   nil,   135,
   135,   nil,   nil,   nil,   147,   135,   147,   147,   147,   147,
   147,   147,   147,   nil,   147,   147,   nil,   nil,   nil,   nil,
   nil,   147,   147,   149,   nil,   nil,   nil,   147,   nil,   149,
   149,   149,   149,   149,   149,   149,   149,   149,   149,   149,
   149,   149,   149,   149,   149,   149,   149,   151,   nil,   151,
   151,   151,   151,   151,   151,   151,   nil,   151,   151,   nil,
   nil,   nil,   nil,   nil,   151,   151,   nil,   nil,   nil,   160,
   151,   160,   160,   160,   160,   160,   160,   160,   nil,   160,
   160,   nil,   nil,   nil,   nil,   nil,   160,   160,   nil,   nil,
   nil,   162,   160,   162,   162,   162,   162,   162,   162,   162,
   nil,   162,   162,   nil,   nil,   nil,   nil,   nil,   162,   162,
   nil,   nil,   nil,   163,   162,   163,   163,   163,   163,   163,
   163,   163,   nil,   163,   163,   nil,   nil,   nil,   nil,   nil,
   163,   163,   nil,   nil,   nil,   164,   163,   164,   164,   164,
   164,   164,   164,   164,   nil,   164,   164,   nil,   nil,   nil,
   nil,   nil,   164,   164,   127,   nil,   nil,   nil,   164,   nil,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   126,   nil,   nil,
   nil,   nil,   nil,   126,   126,   126,   126,   126,   126,   126,
   126,   126,   126,   126,   126,   126,   126,   126,   126,   129,
   nil,   nil,   nil,   nil,   nil,   129,   129,   129,   129,   129,
   129,   129,   129,   129,   129,   129,   129,   129,   129,   129,
   130,   nil,   nil,   nil,   nil,   nil,   130,   130,   130,   130,
   130,   130,   130,   130,   130,   130,   130,   130,   130,   130,
   128,   nil,   nil,   nil,   nil,   nil,   128,   128,   128,   128,
   128,   128,   128,   128,   128,   128,   128,   128,   128,   120,
   nil,   nil,   nil,   nil,   nil,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   121,   nil,   nil,   nil,
   nil,   nil,   121,   121,   121,   121,   121,   121,   121,   121,
   121,   121,   121,   122,   nil,   nil,   nil,   nil,   nil,   122,
   122,   122,   122,   122,   122,   122,   122,   122,   122,   122,
   123,   nil,   nil,   nil,   nil,   nil,   123,   123,   123,   123,
   123,   123,   123,   123,   123,   123,   123,   124,   nil,   nil,
   nil,   nil,   nil,   124,   124,   124,   124,   124,   124,   124,
   124,   124,   124,   124,   125,   nil,   nil,   nil,   nil,   nil,
   125,   125,   125,   125,   125,   125,   125,   125,   125,   125,
   125 ]

racc_action_pointer = [
   -22,    27,   874,    28,     1,   nil,   888,   nil,   -27,    -2,
    -1,     1,   902,   nil,    -2,    -1,    20,   nil,   nil,   nil,
   nil,    -2,    26,    94,   104,    20,    21,   114,   924,    45,
   nil,   nil,   nil,   nil,   nil,    49,    50,   119,   nil,   nil,
   nil,   nil,   126,   180,   nil,   190,   nil,   195,   221,   248,
   262,   275,   289,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   303,    73,   793,    79,   nil,   nil,
   316,    70,   330,    71,   344,   967,   824,    83,   991,   357,
   371,   385,   398,   412,   426,   439,   453,   467,   480,   494,
   508,   521,   535,   549,   562,   576,   590,   603,   617,   139,
   145,   147,   169,   170,    -3,   119,   130,   124,    21,   nil,
  1015,   nil,   849,   128,   nil,   149,   159,   185,   186,   187,
  1316,  1333,  1350,  1367,  1384,  1401,  1234,  1211,  1297,  1256,
  1277,   103,   125,   874,   nil,  1015,   631,   151,   644,   146,
   145,   658,   nil,   164,   736,   672,    47,  1037,   146,  1080,
   nil,  1080,   685,   760,    94,   nil,   nil,   nil,    71,   -17,
  1102,   nil,  1124,  1146,  1168,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -77,   -77,   -77,   -77,   -77,    -2,    -5,    -4,    -7,   -77,
   -77,   -77,   -14,   -15,   -77,   -77,   -77,   -19,   -20,   -21,
   -22,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,
   -72,   169,    -1,    -3,    -6,   -12,   -12,   -77,   -13,   -16,
   -17,   -18,   -77,   -77,   -56,   -77,   -24,   -60,   -77,   -77,
   -77,   -77,   -77,   -48,   -49,   -50,   -51,   -52,   -57,   -73,
   -74,   -75,   -76,   -58,   -77,   -77,   -77,   -77,   -70,   -71,
   -77,   -77,   -77,   -77,   -77,   -54,   -77,   -24,   -77,   -77,
   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,
   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -43,
   -44,   -45,   -46,   -47,   -77,   -77,   -77,   -77,   -77,    -8,
   -11,    -9,   -77,   -77,   -23,   -25,   -26,   -27,   -28,   -29,
   -30,   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,
   -40,   -41,   -42,   -77,   -59,   -77,   -77,   -77,   -77,   -77,
   -12,   -77,   -53,   -63,   -77,   -77,   -77,   -77,   -77,   -55,
   -61,   -77,   -77,   -77,   -77,   -68,   -10,   -62,   -77,   -77,
   -77,   -69,   -77,   -77,   -77,   -67,   -64,   -65,   -66 ]

racc_goto_table = [
    21,     1,    67,     4,    21,    71,    73,    35,    36,    37,
    21,     7,    12,    58,    63,    33,    12,    66,     6,     8,
    44,    38,    12,   105,    34,     8,    21,    77,   150,   nil,
   nil,   nil,    75,    76,   nil,    78,   nil,   nil,    99,   100,
   101,   102,   103,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   104,   nil,   nil,   nil,   nil,   nil,
   108,   nil,   110,    21,   112,   nil,   nil,   nil,   nil,   115,
   116,   117,   118,   119,   120,   121,   122,   123,   124,   125,
   126,   127,   128,   129,   130,   131,   132,   133,   134,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   137,   nil,   nil,   nil,   nil,   143,
   148,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   155,   nil,   nil,   nil,   157,   144,   nil,   146,   nil,
   nil,   149,   nil,    21,   165,   153,   166,   167,   168,   nil,
   nil,   nil,   158,   nil,   nil,    21,   nil,   nil,   nil,    21,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,
    21,    21,    21 ]

racc_goto_check = [
     6,     1,    23,     2,     6,     7,     7,     6,     6,     6,
     6,     4,     9,    22,    22,     4,     9,     8,     3,     5,
     6,     4,     9,    10,     3,     5,     6,    17,    24,   nil,
   nil,   nil,     8,     8,   nil,     8,   nil,   nil,     8,     8,
     8,     8,     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,   nil,   nil,
     8,   nil,     8,     6,     8,   nil,   nil,   nil,   nil,     8,
     8,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,     8,     8,     8,     8,     8,    22,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,    23,
     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    23,   nil,   nil,   nil,    23,     8,   nil,     8,   nil,
   nil,     8,   nil,     6,    23,     8,    23,    23,    23,   nil,
   nil,   nil,     8,   nil,   nil,     6,   nil,   nil,   nil,     6,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,   nil,
     6,     6,     6 ]

racc_goto_pointer = [
   nil,     1,     1,    16,     9,    17,    -2,   -30,   -10,    10,
   -42,   nil,   nil,   nil,   nil,   nil,   nil,   -18,   nil,   nil,
   nil,   nil,   -10,   -26,  -115 ]

racc_goto_default = [
   nil,    13,   nil,   nil,   nil,    69,    53,   nil,    47,    68,
    14,    15,    16,    17,    18,    19,    20,    46,    54,    55,
    56,    57,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 60, :_reduce_1,
  2, 60, :_reduce_2,
  2, 61, :_reduce_3,
  1, 61, :_reduce_4,
  1, 61, :_reduce_5,
  2, 62, :_reduce_6,
  1, 62, :_reduce_7,
  4, 64, :_reduce_8,
  4, 64, :_reduce_9,
  7, 64, :_reduce_10,
  2, 66, :_reduce_11,
  0, 66, :_reduce_12,
  2, 63, :_reduce_13,
  1, 63, :_reduce_14,
  1, 68, :_reduce_15,
  2, 68, :_reduce_16,
  2, 68, :_reduce_17,
  2, 68, :_reduce_18,
  1, 68, :_reduce_19,
  1, 68, :_reduce_20,
  1, 68, :_reduce_21,
  1, 68, :_reduce_22,
  3, 67, :_reduce_23,
  1, 67, :_reduce_24,
  3, 76, :_reduce_25,
  3, 76, :_reduce_26,
  3, 76, :_reduce_27,
  3, 76, :_reduce_28,
  3, 76, :_reduce_29,
  3, 76, :_reduce_30,
  3, 76, :_reduce_31,
  3, 76, :_reduce_32,
  3, 76, :_reduce_33,
  3, 76, :_reduce_34,
  3, 76, :_reduce_35,
  3, 76, :_reduce_36,
  3, 76, :_reduce_37,
  3, 76, :_reduce_38,
  3, 76, :_reduce_39,
  3, 76, :_reduce_40,
  3, 76, :_reduce_41,
  3, 76, :_reduce_42,
  2, 76, :_reduce_43,
  2, 76, :_reduce_44,
  2, 76, :_reduce_45,
  2, 76, :_reduce_46,
  2, 76, :_reduce_47,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  4, 76, :_reduce_53,
  3, 69, :_reduce_54,
  6, 69, :_reduce_55,
  2, 70, :_reduce_56,
  2, 71, :_reduce_57,
  2, 71, :_reduce_58,
  3, 81, :_reduce_59,
  1, 81, :_reduce_60,
  6, 72, :_reduce_61,
  2, 83, :_reduce_62,
  0, 83, :_reduce_63,
  9, 73, :_reduce_64,
  9, 74, :_reduce_65,
  9, 74, :_reduce_66,
  8, 75, :_reduce_67,
  6, 75, :_reduce_68,
  7, 75, :_reduce_69,
  1, 82, :_reduce_70,
  1, 82, :_reduce_71,
  1, 65, :_reduce_72,
  1, 77, :_reduce_73,
  1, 78, :_reduce_74,
  1, 79, :_reduce_75,
  1, 80, :_reduce_76 ]

racc_reduce_n = 77

racc_shift_n = 169

racc_token_table = {
  false => 0,
  :error => 1,
  "RIGHTBRACKET" => 2,
  "LEFTBRACKET" => 3,
  "NOT" => 4,
  "NOTBITS" => 5,
  "DOLLAR" => 6,
  "AT" => 7,
  "UMINUS" => 8,
  "PRODUCT" => 9,
  "DIVISION" => 10,
  "MODULE" => 11,
  "PLUS" => 12,
  "MINUS" => 13,
  "LEFTDISPLACEMENT" => 14,
  "RIGHTDISPLACEMENT" => 15,
  "LESSTHAN" => 16,
  "LESSOREQUALTHAN" => 17,
  "MORETHAN" => 18,
  "MOREOREQUALTHAN" => 19,
  "EQUALS" => 20,
  "NOTEQUAL" => 21,
  "ANDBITS" => 22,
  "XORBITS" => 23,
  "ORBITS" => 24,
  "AND" => 25,
  "OR" => 26,
  "BEGIN" => 27,
  "END" => 28,
  "INT" => 29,
  "BOOL" => 30,
  "BITS" => 31,
  "INPUT" => 32,
  "OUTPUT" => 33,
  "OUTPUTLN" => 34,
  "IF" => 35,
  "ELSE" => 36,
  "FOR" => 37,
  "FORBITS" => 38,
  "AS" => 39,
  "FROM" => 40,
  "GOING" => 41,
  "HIGHER" => 42,
  "LOWER" => 43,
  "REPEAT" => 44,
  "WHILE" => 45,
  "DO" => 46,
  "TRUE" => 47,
  "FALSE" => 48,
  "BOOLEAN" => 49,
  "IDENTIFIER" => 50,
  "BITARRAY" => 51,
  "INTEGER" => 52,
  "STRING" => 53,
  "ASSIGN" => 54,
  "SEMICOLON" => 55,
  "COMMA" => 56,
  "LEFTPARENTHESIS" => 57,
  "RIGHTPARENTHESIS" => 58 }

racc_nt_base = 59

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"RIGHTBRACKET\"",
  "\"LEFTBRACKET\"",
  "\"NOT\"",
  "\"NOTBITS\"",
  "\"DOLLAR\"",
  "\"AT\"",
  "\"UMINUS\"",
  "\"PRODUCT\"",
  "\"DIVISION\"",
  "\"MODULE\"",
  "\"PLUS\"",
  "\"MINUS\"",
  "\"LEFTDISPLACEMENT\"",
  "\"RIGHTDISPLACEMENT\"",
  "\"LESSTHAN\"",
  "\"LESSOREQUALTHAN\"",
  "\"MORETHAN\"",
  "\"MOREOREQUALTHAN\"",
  "\"EQUALS\"",
  "\"NOTEQUAL\"",
  "\"ANDBITS\"",
  "\"XORBITS\"",
  "\"ORBITS\"",
  "\"AND\"",
  "\"OR\"",
  "\"BEGIN\"",
  "\"END\"",
  "\"INT\"",
  "\"BOOL\"",
  "\"BITS\"",
  "\"INPUT\"",
  "\"OUTPUT\"",
  "\"OUTPUTLN\"",
  "\"IF\"",
  "\"ELSE\"",
  "\"FOR\"",
  "\"FORBITS\"",
  "\"AS\"",
  "\"FROM\"",
  "\"GOING\"",
  "\"HIGHER\"",
  "\"LOWER\"",
  "\"REPEAT\"",
  "\"WHILE\"",
  "\"DO\"",
  "\"TRUE\"",
  "\"FALSE\"",
  "\"BOOLEAN\"",
  "\"IDENTIFIER\"",
  "\"BITARRAY\"",
  "\"INTEGER\"",
  "\"STRING\"",
  "\"ASSIGN\"",
  "\"SEMICOLON\"",
  "\"COMMA\"",
  "\"LEFTPARENTHESIS\"",
  "\"RIGHTPARENTHESIS\"",
  "$start",
  "S",
  "bloquePrincipal",
  "declaraciones",
  "instrucciones",
  "declaracion",
  "identificador",
  "init",
  "expresionP",
  "instruccion",
  "asignacion",
  "entrada",
  "salida",
  "condicional",
  "iteracionFor",
  "iteracionForBits",
  "iteracionWhile",
  "expresion",
  "entero",
  "booleano",
  "arregloBits",
  "cadena",
  "expMultiple",
  "instruccionDeclaracion",
  "clausuraElse" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 49)
  def _reduce_1(val, _values, result)
    result = NodoInicial.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 50)
  def _reduce_2(val, _values, result)
    result = NodoInicial.new(nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 54)
  def _reduce_3(val, _values, result)
    result = NodoBloquePrincipal.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 55)
  def _reduce_4(val, _values, result)
    result = NodoBloquePrincipal.new(nil, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 56)
  def _reduce_5(val, _values, result)
    result = NodoBloquePrincipal.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 60)
  def _reduce_6(val, _values, result)
    result = NodoDeclaraciones.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 61)
  def _reduce_7(val, _values, result)
    result = NodoDeclaraciones.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 65)
  def _reduce_8(val, _values, result)
    result = NodoDeclaracion.new(val[0], val[1], nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 66)
  def _reduce_9(val, _values, result)
    result = NodoDeclaracion.new(val[0], val[1], nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 67)
  def _reduce_10(val, _values, result)
    result = NodoDeclaracion.new(val[0], val[1], val[3], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 71)
  def _reduce_11(val, _values, result)
    result = NodoInit.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 72)
  def _reduce_12(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 76)
  def _reduce_13(val, _values, result)
    result = NodoInstrucciones.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 77)
  def _reduce_14(val, _values, result)
    result = NodoInstrucciones.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 81)
  def _reduce_15(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 82)
  def _reduce_16(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 83)
  def _reduce_17(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 84)
  def _reduce_18(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 85)
  def _reduce_19(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 86)
  def _reduce_20(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 87)
  def _reduce_21(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 88)
  def _reduce_22(val, _values, result)
    result = NodoInstruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 92)
  def _reduce_23(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 93)
  def _reduce_24(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 97)
  def _reduce_25(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 98)
  def _reduce_26(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 99)
  def _reduce_27(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 100)
  def _reduce_28(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 101)
  def _reduce_29(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 102)
  def _reduce_30(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 103)
  def _reduce_31(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 104)
  def _reduce_32(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 105)
  def _reduce_33(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Aritmetica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 106)
  def _reduce_34(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Comparacion', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 107)
  def _reduce_35(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Comparacion', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 108)
  def _reduce_36(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Logica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 109)
  def _reduce_37(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Logica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 110)
  def _reduce_38(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Bits', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 111)
  def _reduce_39(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Bits', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 112)
  def _reduce_40(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'Bits', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 113)
  def _reduce_41(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'BitsInt', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 114)
  def _reduce_42(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new(val[1]), val[2], 'BitsInt', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 115)
  def _reduce_43(val, _values, result)
    result = NodoExpresionUn.new(NodoOperador.new(val[0]), val[1], nil, 'Aritmetica', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 116)
  def _reduce_44(val, _values, result)
    result = NodoExpresionUn.new(NodoOperador.new(val[0]), val[1], nil, 'Aritmetica', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 117)
  def _reduce_45(val, _values, result)
    result = NodoExpresionUn.new(NodoOperador.new(val[0]), val[1], nil, 'Logica', 'BOOL')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 118)
  def _reduce_46(val, _values, result)
    result = NodoExpresionUn.new(NodoOperador.new(val[0]), val[1], nil, 'Bits', 'BITS')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 119)
  def _reduce_47(val, _values, result)
    result = NodoExpresionUn.new(NodoOperador.new(val[0]), val[1], nil, 'Bits', 'INT')
    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

module_eval(<<'.,.,', 'Parser.y', 125)
  def _reduce_53(val, _values, result)
    result = NodoExpresionBin.new(val[0], NodoOperador.new('ACCESS'), val[2], 'BitsInt', 'INT')
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 129)
  def _reduce_54(val, _values, result)
    result = NodoAsignacion.new(val[0], val[2], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 130)
  def _reduce_55(val, _values, result)
    result = NodoAsignacion.new(val[0], val[5], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 134)
  def _reduce_56(val, _values, result)
    result = NodoEntrada.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 138)
  def _reduce_57(val, _values, result)
    result = NodoSalida.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 139)
  def _reduce_58(val, _values, result)
    result = NodoSalida.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 143)
  def _reduce_59(val, _values, result)
    result = NodoExpMultiple.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 144)
  def _reduce_60(val, _values, result)
    result = NodoExpMultiple.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 148)
  def _reduce_61(val, _values, result)
    result = NodoCondicional.new(val[2], val[4], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 152)
  def _reduce_62(val, _values, result)
    result = NodoClausuraElse.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 153)
  def _reduce_63(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 157)
  def _reduce_64(val, _values, result)
    result = NodoFor.new(val[2], val[4], val[6], val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 161)
  def _reduce_65(val, _values, result)
    result = NodoForBits.new(val[1], val[3], val[5], val[7], val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 162)
  def _reduce_66(val, _values, result)
    result = NodoForBits.new(val[1], val[3], val[5], val[7], val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 166)
  def _reduce_67(val, _values, result)
    result = NodoWhile.new(val[0], val[1], val[4], val[6], val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 167)
  def _reduce_68(val, _values, result)
    result = NodoWhile.new(nil, nil, val[2], val[4], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 168)
  def _reduce_69(val, _values, result)
    result = NodoWhile.new(val[0], val[1], val[4], nil, nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 172)
  def _reduce_70(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 173)
  def _reduce_71(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 177)
  def _reduce_72(val, _values, result)
    result = NodoId.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 181)
  def _reduce_73(val, _values, result)
    result = NodoInt.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 185)
  def _reduce_74(val, _values, result)
    result = NodoBool.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 189)
  def _reduce_75(val, _values, result)
    result = NodoBits.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 193)
  def _reduce_76(val, _values, result)
    result = NodoStr.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser


