		superRegex = {"Spaces": /\A(\s)*/,
					  "Comments": /\A#/,
					  "bool": /\Atrue\b | \Afalse\b/,
					  "identifier": /\A[a-zA-Z][a-zA-Z0-9_]*/,
					  "bits": /\A0b[01]+/,
					  "integer": /\A(\d)+/,
					  "string": /\A"(\\.|[^\\"\n])*"/,
					  "left bracket": /\A\[/,
					  "right bracket": /\A\]/,
					  "not": /\A\!/,
					  "not bits": /\A\~/,
					  "dollar": /\A\$/,
					  "at": /\A\@/,
					  "minus": /\A\-/,
					  "product": /\A\*/,
					  "division": /\A\//,
					  "module": /\A\%/,
					  "plus": /\A\+/,
					  "left displacement": /\A\<\</,
					  "right displacement": /\A\>\>/,
					  "less than": /\A\</,
					  "less or equal than": /\A\<\=/,
					  "more than": /\A\>/,
					  "more or equal than": /\A\>\=/,
					  "equals": /\A\=\=/,
					  "not equal": /\A\!\=/,
					  "and bits": /\A\&/,
					  "xor bits": /\A\^/,
					  "or bits": /\A\|/,
					  "and": /\A\&\&/,
					  "or": /\A\|\|/,
					  "semicolon": /\A\;/,
					  "comma": /\A\,/,
					  "left parenthesis": /\A\(/,
					  "right parenthesis": /\A\)/                     
					  }
